[snowflake]
account = "dic19309.us-east-1"
user = "STREAMLIT_APP_USER"
role = "STREAMLIT_APP_ROLE"
warehouse = "COMPUTE_WH"
database = "HEALTH_CARE"
schema = "HEALTH_CARE_SCHEMA"
private_key = -----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDGO8Oo+Ggu8etT
T3NvVtD5mUAXSnHPO0sAJGo+I8HTxWf/tmRjgOPKr+oBGvU6LVfJiJv+/kdcyqfm
Iczl5tmgKp10UzbxPrADnz8EteJ1DHl5XkXM8WO6a7ikiOp7lnZJ+KPADQ+VIYxb
XOfMS5i74U8qiV9PcENlZ1exO5VtcTtg/K0LpEFoBoo1KFrZK8IqIl76XWrpR7DW
O6ridhCLaGTxxGFibZhEX0crtBGd6IHZX0Z3nQ8vtNfjelktPqGmuQk/i9XUlhND
/p0sOGlksyD0DyTJIuRrjC4NoW388TLSKHjlICg+UiGUCPoDasnT+ovjoOSZBwlB
8u4BXEmNAgMBAAECggEACRpeekhp9FnsngdEfETm1MdqT4d+IW+OGqQRcugOcwya
IX59LqqRC1I3szRLNZA2e004KKYBneu6eRFtSNNog/fhAiH+IGbqC0iJSsyVaR2Z
CG9BUk91bm6a7IdTCTjYFr6BuoR/BjCjsuBZzqJcEaifi4sCYvH7TlFIEB311zAq
uq52HiBSyMCveqofxk4+OPuDPo4yC4Yva1ZU/JxK1HRgF7BvLCIbEbssKhimppp2
ZeH8sQZDFI+NczbT4G/KW5BoKZXTiXxITze6tbYNzJnyB+Kk0KjBUVIU4Ur9FAWz
d5Intd86SNzoWzjxckd2fp/3f38cYnIW+ZJwDwbFqwKBgQDuH9T4tAD/sI8j6Vqs
e/Tkvhdih8c6nvSzqRPKuGUcmx8y0v6OyaNOnqsdQgy2BooVoyRoG5n80qotwDRr
5VVeQpFqdwsllJC+cHSvhe+xDZ4IKkalv57Gp/loR/gjNHT2jEfa8ITeyYlVp6/m
uYYpkYat4HzswPMf2iP10KDGcwKBgQDVHVOzGfirJaB3PJF2A+VJQ5MyX1MmUbSF
BYmAYx7SyQLtzvAceBoaXZdrxZoxwr3oKcch+/qOcb5RmyWuDk8EaeqnE97NJTLQ
w7atmfhKjUo1Qap+gEJoBLLINQVtZzvCA03xW8B9NbxQ6OCcQ+deB6JYH+zmOyMP
VIyF/rqv/wKBgBc12xhy0zYZC5rAgCoX2wMA1F6yRWUdYVSxwlAcMR7cr+nQTyez
18suBBfR/FMxx/vb7wyGxDe0gQn8lh9+Nxf8/ReXiuqa1JD7fSQutfJYFXNOS5yU
VPGgJdtYSIOF9XCis85Pa2Qb2NsUgTzIEJ+0o6AHJaYeGJSeOqsXLtSpAoGBAIPC
sQgPq53tEowF541GlVE5tV00cI1FgM2pgbzeC6WY3/W1tuBzJPheGwtnzZCsbYuH
oPWS+/NrwZZkzOQTNqls7sZD08GUGRnXly83/bniJxpMMiQqGmSDWyHLHkLoy5qF
PoBWEOmY+ogvowcaOIb7Q1Umz+n8cA2/YW5K8pNzAoGBANS6Di3tEH93C9bNbvKh
I5uTauMqBcKhNOzhL8rl/pv5KY2iOMiZHhzked8a2IWJwrh8fyjr7M9ncD9KAWpH
lrU3H1VnlmTKayXM0VcVx5lEM23omngsKRKu5nsxs1/e9sO78kR11FDk1bupx9Pn
fVr21ZQoMSHUuCEOOxaEsUXe
-----END PRIVATE KEY-----
